---
title: "Mutually Exclusive Phenotypes"
author: "Amandeep Rathee and Hilmar Lapp"
date: "`r format(Sys.Date(), '%B-%d-%Y')`"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rphenoscape)
library(tidyverse)
library(microbenchmark)
```


This vignette showcases a function `are_mutually_exclusive` that establishes whether two phenotypes are mutually exclusive based on the phenoscape KB data.


## 1. Test of mutual exclusivity among two pehnotypes. 

```{r include=TRUE, eval=TRUE, echo=TRUE, render=FALSE}

are_mutually_exclusive <- function(phenotype.a, phenotype.b, studies=NULL, charstates=NULL, verbose=FALSE){
    
    # mutually_exclusive takes three values:
    # -1: default; we assume that before checking mutual exclusion, phenotypes are neither mutually exclusive nor mutually compatible
    #  0: data suggests mutual compatibility
    #  1: data suggests mutual exclusion
    #  2: data suggests mutual compatibility within same taxa
    
    # set mutual exclusivity to default value
    mutually_exclusive <- -1
    
    # convert to phenotype object
    if(!is.phenotype(phenotype.a)){
        phenotype.a <- as.phenotype(phenotype.a, withTaxa=TRUE)
    }
    
    if(!is.phenotype(phenotype.b)){
        phenotype.b <- as.phenotype(phenotype.b, withTaxa=TRUE)
    }
    
    # get charstates dataframe
    if(is.null(charstates)){
        character_states <- charstates(list(phenotype.a, phenotype.b))
    } else{
        character_states = charstates
    }
    
    # filter the character state dataframe based on phenotypes and studies (optional)
    if(is.null(studies)){
        charstates.a <- character_states[character_states$phenotype.id == phenotype.a$id, ]
        charstates.b <- character_states[character_states$phenotype.id == phenotype.b$id, ]
    } else {
        charstates.a <- character_states[(character_states$phenotype.id == phenotype.a$id) & (character_states$study.id %in% studies), ]
        charstates.b <- character_states[(character_states$phenotype.id == phenotype.b$id) & (character_states$study.id %in% studies), ]   
    }
    
    # get states associated with both phenotypes
    states.a <- charstates.a$state.id
    states.b <- charstates.b$state.id
    
    # determine mutual exclusivity only if both study vectors are non-empty
    if((length(states.a) > 0) & (length(states.b) > 0)){ 
        
        # get characters
        chars.a <- unique(charstates.a$character.id)
        chars.b <- unique(charstates.b$character.id)
        
        # check intersection of characters in both phenotypes
        char_matches <- sum(chars.a %in% chars.b)
        
        if(char_matches == 0){ 
            # CASE 1: if no characters match then check whether phenotypes have common taxa
            
            if(length(intersect(phenotype.a$taxa$id, phenotype.b$taxa$id)) > 0){
                # if phenotypes have common taxa then mutually compatible
                if(verbose){cat("Phenotypes occur in the same taxa but no characters match.\n")}
                mutually_exclusive <- 2
            } else {
                # if phenotypes occur in mutually exclusive taxa then they are mutually exclusive
                if(verbose){cat("Phenotypes occur in two different mutually exclusive taxa and no characters match.\n")}
                mutually_exclusive <- 1
            }
            
        } else { 
            # CASE 2: if one or more characters match --> investigate further
            
            if(intersection_length(charstates.a, charstates.b) == 0){
                # CASE 2-I: for matched characters, if no states are common among the matched characters --> phenotypes are mutually exclusive
                if(verbose){cat("Character match but no state match.\n")}
                mutually_exclusive <- 1
                
            } else {
                # CASE 2-II: if, for any matched characters, any two corresponding states match --> phenotypes are mutually compatible
                if(verbose){cat("Character match and state match.\n")}
                mutually_exclusive <- 0
            }
        }
        
        if(mutually_exclusive == -1){warning('Insufficient evidence to determine mutual exclusivity.')}  
        
    } else {
        if(length(states.a) == 0){
            mutually_exclusive <- NA
            warning("Phenotype A is not part of any of the studies passed. Both phenotypes are required to be part of at least one study.")
            
        } else if (length(states.b) == 0){
            mutually_exclusive <- NA
            warning("Phenotype B is not part of any of the studies passed. Both phenotypes are required to be part of at least one study.")
        } else {
            mutually_exclusive <- NA
            warning("Phenotypes A and B are not part of any of the studies passed. Both phenotypes are required to be part of at least one study.")
        }
    }
    
    
    mutually_exclusive
}

intersection_length <- function(charstate.a, charstate.b){
    
    # find common character-state pairs among phenotype A and B
    # finding for commom character-state pair is equivalent to looking for common state ids because state ids are unique
    length(intersect(charstate.a[, c('state.id')], charstate.b[, c('state.id')]))
}

```


```{r include=TRUE, eval=FALSE, echo=TRUE, render=FALSE}
# get phenotypes
phenotypes <- get_phenotypes(entity = "hyomandibular bone", taxon = "Hypancistrus")
phenotypes <- c(phenotypes$id[phenotypes$label == 'hyomandibular bone in contact with prootic bone'],
                phenotypes$id[phenotypes$label == 'hyomandibular bone in contact with quadrate bone'],
                phenotypes$id[phenotypes$label == 'hyomandibular bone position opercle'],
                phenotypes$id[phenotypes$label == 'hyomandibular bone structure metapterygoid'])
# get studies
studies <- pk_get_study_list(entity = "hyomandibular bone", taxon = "Hypancistrus")
study <- studies$id[studies$label == 'Armbruster (2004)']

# check mutual exclusivity
are_mutually_exclusive(phenotypes[1], phenotypes[2], study)

```


## 2. Test of mutual exclusivity among more than two phenotypes. 

```{r include=TRUE, eval=TRUE, echo=TRUE, render=FALSE}

mutual_exclusivity_matrix <- function(phenotypes, studies=NULL, progress_bar=TRUE){
    # return square matrix of size length(phenotypes) and a dataframe that contains mutual exclusive pairs of phenotypes
    
    # matrix has the following values
    # NA: phenotypes present in the row and column are not part of the studies provided
    # -1: default; insufficient data to conclude mutual exclusivity or compatibility
    #  0: phenotypes belonging to row and column are mutually compatible
    #  1: phenotypes belonging to row and column are mutually exclusive
    #  2: phenotypes belonging to row and column are mutually compatible (within same taxa)
    
    # each row of dataframe represents a mutually exclusive pair with label and ids of both phenotypes
    
    # initialize matrix
    num_phenotypes <- length(phenotypes)
    mutual_exclusivity_matrix <- matrix(-1, nrow=num_phenotypes, ncol=num_phenotypes)
    
    # initialize variables to keep track of progress of the function
    iteration <- 1
    total_iterations <- choose(num_phenotypes, 2) + num_phenotypes
    num_mutual_exclusive_pairs <- 0
    num_mutual_compatible_pairs <- 0
    num_inconclusive_evidence <- 0
    first_mutual_exclusive_pair <- FALSE
    
    # convert to phenotype objects
    if(!all(sapply(phenotypes, is.phenotype))){
        phenotypes <- as.phenotype(phenotypes)   
    }
    
    # load charstates dataframe
    character_states <- charstates(phenotypes)
    
    # find mutual exclusivity for each pair in the phenotype vector
    for (row in 1:num_phenotypes) {
        for (column in row:num_phenotypes) {
            
            # print progress of the loop
            if(progress_bar == TRUE){
                cat('\014')
                cat(paste0(round(iteration / (total_iterations) * 100, 4), '% completed\n', 
                           'Mutually exclusive pairs = ', num_mutual_exclusive_pairs, '\n',
                           'Mutually compatible pairs = ', num_mutual_compatible_pairs, '\n',
                           'Inconclusive evidence = ', num_inconclusive_evidence, '\n'))
                iteration <- iteration + 1
            }
            
            if(row != column){ # compute mutual exclusivity among distinct phenotypes only
                mutual_exclusivity <- are_mutually_exclusive(phenotypes[[row]], phenotypes[[column]], 
                                                             studies=studies,
                                                             charstates=character_states,
                                                             verbose=FALSE)
                #print(mutual_exclusivity)
                mutual_exclusivity_matrix[row, column] <- mutual_exclusivity
                mutual_exclusivity_matrix[column, row] <- mutual_exclusivity
                
                if(mutual_exclusivity == 1){
                    num_mutual_exclusive_pairs <- num_mutual_exclusive_pairs + 1
                    
                    # append row of mutually exclusive pair to dataframe
                    #print(phenotypes[row])
                    dataframe_row <- c(phenotypes[[row]]$id,
                                       phenotypes[[row]]$label,
                                       #character_states[character_states$phenotype.id == row, ][, c("phenotype.label")],
                                       phenotypes[[column]]$id,
                                       phenotypes[[column]]$label
                                       #character_states[character_states$phenotype.id == column, ][, c("phenotype.label")]
                                       )
                    
                    if(first_mutual_exclusive_pair==FALSE){ # create dataframe if first mutually exclusive pair
                        mutually_exclusive_pairs <- data.frame(id.1    = dataframe_row[1],
                                                               label.1 = dataframe_row[2],
                                                               id.2    = dataframe_row[3],
                                                               label.2 = dataframe_row[4],
                                                               stringsAsFactors = FALSE)
                        first_mutual_exclusive_pair <- TRUE
                    } else { # append to existing dataframe for all subsequent mutually exclusive pairs
                        mutually_exclusive_pairs <- rbind(mutually_exclusive_pairs, dataframe_row)
                    }
                
                } else if(mutual_exclusivity == -1){
                    num_inconclusive_evidence <- num_inconclusive_evidence + 1
                
                } else if(mutual_exclusivity == 0 | mutual_exclusivity == 2){
                    num_mutual_compatible_pairs <- num_mutual_compatible_pairs + 1
                }
                
            } else if(row == column){
                mutual_exclusivity_matrix[row, column] <- 0
            }
        }
    }
    
    # set header for matrix
    rownames(mutual_exclusivity_matrix) <- 1:length(phenotypes)
    colnames(mutual_exclusivity_matrix) <- 1:length(phenotypes)
    
    # return a list containing the matrix and the dataframe
    list(matrix=mutual_exclusivity_matrix, 
         mutually_exclusive_pairs=data.frame(mutually_exclusive_pairs))
}

```


## Find mutual exclusive phenotypes in the Dillman et al. (2016) study

```{r include=TRUE, eval=TRUE, echo=TRUE, render=FALSE}
# get study
studies <- pk_get_study_list()
study <- studies$id[studies$label == 'Dillman et al. (2016)']

# get phenotypes
phenotypes <- get_phenotypes(study=study)
phenotypes <- as.phenotype(phenotypes)

# test mutual exclusivity
n <- 5
me <- mutual_exclusivity_matrix(phenotypes[1:n], study, progress_bar=FALSE)

# get matrix
me$matrix

# get phenotype pairs
me$mutually_exclusive_pairs

```

