version: 2

steps: &steps
  steps:
    - restore_cache:
        keys:
          - cache-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_JOB }}
    - checkout
    - run:
        name: Update openssl to avoid SSL errors after installing curl R module for R 3
        command: apt-get update && apt-get install -y libcurl4-openssl-dev
    - run:
        name: Install package dependencies
        command: R -e "devtools::install_deps(dep = TRUE, repos = 'https://cloud.r-project.org')"
    - run:
        name: Build package
        command: R CMD build .
    - run:
        name: Check package
        command: R CMD check --as-cran --no-manual *tar.gz
    - store_artifacts:
        path: rphenoscape.Rcheck/
    - save_cache:
        key: cache-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_JOB }}
        paths:
          - "/usr/local/lib/R/site-library"

jobs:
  r4:
    docker:
      - image: rocker/verse:4
    <<: *steps
  r3:
    docker:
      - image: rocker/verse:3.6.3
    <<: *steps

workflows:
  version: 2
  all:
    jobs:
      - r4
      - r3
